### ISSUE TITLE
Runkit + APC

### ISSUE THREAD

**Issue by tcz** [zenovich/runkit#14]
Hi,

Using APC with runkit's runkit_method_redefine makes the script execution crash (silently stop).
I'm happy to provide any more information, just tell me what, 'cause I'm not quite sure.

**Comment by everflux** [comment]
Using php-fpm with zend opcache leads to the problem as well that after two times the method renaming does no longer work until the php process is restarted.

**Comment by zenovich** [comment]
@everflux, could you please provide me with your php's version, your zend opcache's version, your zend opcache's configuration, and a test example. Unfortunately, I can't reproduce the issue without this info.
