### ISSUE TITLE
Passing a callable to runkit_*_redefine?

### ISSUE THREAD

**Issue by ubermuda** [zenovich/runkit#16]
Hey, this may be completely stupid, I'm not sure so if it is don't hesitate to tell me, but I though it'd be handy to be able to pass a callable to runkit_method_redefine and runkit_function_redefine instead of a string.

What do you think?

**Comment by zenovich** [comment]
Dreams come true! https://github.com/zenovich/runkit/commit/fcc70cd73e8695fe15b22d88b3547b540e72f464
