### ISSUE TITLE
Provide php_runkit.dll

### ISSUE THREAD

**Issue by aimfeld** [zenovich/runkit#22]
Would it be possible to provide the compiled php_runkit.dll? I'm having a hard time creating it myself, and I don't find it anywhere for downloading.

Thanks, Adrian

**Comment by cmb69** [comment]
FTR: there are now DLLs available also on <https://pecl.php.net/package/runkit>.

**Comment by zenovich** [comment]
Wow! :)

**Comment by pilathraj** [comment]
Can you added binary dll files for php7.0+
