### ISSUE TITLE
unable to call runkit_class_adopt multiple times on single class

### ISSUE THREAD

**Issue by kkozlik** [zenovich/runkit#46]
If I call following code using runkit from actual master branch (2013-03-20) the second call of runkit_class_adopt() function does not work. With runkit-1.0.3 it works fine.

```php
class myParent {
  function parentFunc() {
    echo "Parent Function Output\n";
  }
}

class myParent2 {
  function parentFunc2() {
    echo "Parent 2 Function Output\n";
  }
}

class myChild {
}

runkit_class_adopt('myChild','myParent');
print_r(get_class_methods('myChild'));

runkit_class_adopt('myChild','myParent2');
print_r(get_class_methods('myChild'));
```

Expected result
-----------------------
(works with runkit-1.0.3 and older)

<pre>
Array
(
    [0] => parentFunc
)
Array
(
    [0] => parentFunc
    [1] => parentFunc2
)
</pre>

Actual result
------------------
<pre>
Array
(
    [0] => parentFunc
)
Warning: runkit_class_adopt(): Class myChild already has a parent in /var/lib/frafos-sbc-gui/webmin-module/runkit.php.cgi on line 22 
Array
(
    [0] => parentFunc
)
</pre>

**Comment by zenovich** [comment]
runkit_class_adopt did not change classes hierarchy in Runkit below version 1.0.4, so adopted classes in fact had no parent. The bug was fixed here: 7f5b7b16c5fc3ed97370a79822785c657e0ddade
