### ISSUE TITLE
Create a custom PECL channel

### ISSUE THREAD

**Issue by fidian** [zenovich/runkit#51]
It would be great if the install instructions for runkit were as simple as this, assuming you register the "runkit-is-the-best-ever.com" domain:

```
pear config-set auto_discover 1
pear install runkit-is-the-best-ever.com/runkit
```

You could achieve that by making a custom PECL channel by following the instructions here:  http://drewish.com/content/2012/08/publishing-pecl-channels-to-github

**Comment by zenovich** [comment]
@simi I think the time has come :) Tell me please what to do (by a private message).

**Comment by remicollet** [comment]
Simply use "pecl-devel" ML to propose your changes, and to take ownership of this package.

**Comment by zenovich** [comment]
@remicollet I asked there

**Comment by zenovich** [comment]
@fidian, @remicollet Whereas results of discussion on PECL-DEV are unpredictable, I offer to use new PEAR channel server zenovich.github.io/pear
