### ISSUE TITLE
Can't replace a static method without compromising strict standards or doing runkit_import()

### ISSUE THREAD

**Issue by pbudzon** [zenovich/runkit#55]
Hi all,

It would be great if runkit could replace a static methods the same way it replaces the non-static ones. 
**Right now replacing a static method with `runkit_function_redefine()` makes it non-static**, so calling it later as a static generates a Strict Standards warning.

The only way I found to replace a static method (and keep it a static) is to do `runkit_import()` with `RUNKIT_IMPORT_OVERRIDE` flag to replace the original method. 

Also, the behaviour of `runkit_function_redefine()` with static methods is not documented - I think it should!

**Comment by cmb69** [comment]
This ticket can be closed, as the PHP manual [has already been improved](http://svn.php.net/viewvc?view=revision&revision=338018) in this regard.

**Comment by zenovich** [comment]
Thanks, @cmb69. I forgot about that :)
