### ISSUE TITLE
segfault with runkit_class_emancipate, runkit_class_adopt and phpunit

### ISSUE THREAD

**Issue by pprkut** [zenovich/runkit#59]
I'm trying the use runkit to replace the parent class of the class with a Mock version of it, which could make phpunit tests a bit simpler. Unfortunately I get a segfault when I try to execute the code. I put together a small testcase:

```php
<?php

abstract class A
{

    public function to_be_mocked()
    {
        return 1;
    }

}

class B extends A
{

    public function foo()
    {
        return 1 + $this->to_be_mocked();
    }

}

class BTest extends PHPUnit_Framework_TestCase
{

    public function test()
    {
        $parent = $this->getMockForAbstractClass('A');

        runkit_class_emancipate('B');
        runkit_class_adopt('B', get_class($parent));

        $class = new B();

        $class->expects($this->once())
              ->method('to_be_mocked')
              ->will($this-returnValue(2));

        $this->assertSame(3, $class->foo());
    }

}

?>
```

running this using "phpunit testcase.php" gives:

```
PHPUnit 3.7.28 by Sebastian Bergmann.

Segmentation fault
```

Tested with php 5.5.7, phpunit 3.7.28 and runkit master.

**Comment by zenovich** [comment]
runkit_class_adopt doesn't add anything except ancestral methods to the adopted class (see http://php.net/manual/en/function.runkit-class-adopt.php). Trying to access unexisting properties leads to segmentation fault.

**Comment by zenovich** [comment]
Fixed in https://github.com/zenovich/runkit/commit/22628ac773103b1b0073c56b63fcc356a01919c0
