### ISSUE TITLE
Can't add or rename a method that will override a parent method

### ISSUE THREAD

**Issue by baptistepillot** [zenovich/runkit#62]
```php
class Class1 {
	function method()
	{
		echo "method1\n";
	}
}
class Class2 extends Class1 {
}

runkit_method_add('Class2', 'method', '', 'parent::method(); echo "method2\n";');
```
This crashes with a ```runkit_method_add(): Unable to add method to class``` warning.

I can code this workaround in PHP, which seems to be working, but it would be better if runkit correctly detects that the method can be added into ```Class2``` :

```php
runkit_method_rename('Class1', 'method', 'method_tmp');
runkit_method_add('Class2', 'method', '', 'parent::method(); echo "method2\n";');
runkit_method_rename('Class1', 'method_tmp', 'method');
```

Notice : if some parents have this method too, they must be all renamed to tmp, and renamed back from the child to the highest parent.

**Comment by zenovich** [comment]
Fixed
