### ISSUE TITLE
Crashes with runkit_function_rename() on internal functions on php-mod mode

### ISSUE THREAD

**Issue by baptistepillot** [zenovich/runkit#63]
```php
echo "function exists ? " . function_exists('_chop') . "<br>";
echo chop("[ A WORD ") . "]<br>";
if (function_exists('_chop')) echo _chop("[ ANOTHER WORD ") . "]<br>";
runkit_function_rename('chop', '_chop');
```
If I refresh the page executing this script quickly (less than 5 seconds, as apache can use the same process for the next script execution than the previous one) :
- first result is "function exists ?" without any error :
```
function exists ? 
[ A WORD]
```
- after some F5 : next results will be "function exists ? 1" with a warning when I rename saying "_chop() already exists".
```
function exists ? 1
[ A WORD]
[ ANOTHER WORD]
```
It looks like php kept in its memory the _chop function, that keep working well !
This is done with internal functions only. Php defined functions work well.

Tested and reproduced on several computers under xubuntu 13.10 using PHP 5.5.3, installed as an apache module (common use).

And you can make an ```runkit_method_delete('_chop')``` if you want : it will not be here for the current script, but will come back on the next execution using the same process !

I don't want to run php-cgi, sorry :)

**Comment by zenovich** [comment]
Fixed
