### ISSUE TITLE
Protected access function don't work after rename

### ISSUE THREAD

**Issue by baptistepillot** [zenovich/runkit#64]
```php
class Test
{
	protected function func1()
	{
		echo "func1<br>";
	}
}

runkit_method_add('Test', 'func2', '', 'echo "func2<br>"; $this->func1();', RUNKIT_ACC_PUBLIC);
echo "this works :<br>";
(new Test())->func2();

runkit_method_rename('Test', 'func1', '_func1');
runkit_method_redefine('Test', 'func2', '', 'echo "new func2<br>"; $this->_func1();', RUNKIT_ACC_PUBLIC);
echo "this crashes :<br>";
(new Test())->func2();
```
This displays
```Fatal error: Call to protected method Test::func1() from context 'Test' in tests/runkit.php on line 13```

After ```func1``` is renamed, it seems that ```func2``` or any method (declared with or without runkit) from ```Test``` can not access it anymore (with its new name of course). It is a protected method, so it should be found.

How PHP 5.5 does make the protected access control :
https://github.com/php/php-src/blob/250ee4c17a40eb79b4057374384b8669e803636a/Zend/zend_object_handlers.c
and search ```from context```

**Comment by zenovich** [comment]
Fixed
