### ISSUE TITLE
Broken build against 5.6.0RC1

### ISSUE THREAD

**Issue by remicollet** [zenovich/runkit#69]
Because of (from UPGRADING.INTERNALS):

    l. Removal of IS_CONSTANT_ARRAY and IS_CONSTANT_INDEX hack
    
    These two #defines disappeared. Instead we have now IS_CONSTANT_AST which
    covers also the functionality IS_CONSTANT_ARRAY bid and furthermore the
    hack for marking zvals as constant index with IS_CONSTANT_INDEX is now
    superfluous and so removed.
    Please note that IS_CONSTANT_AST now has the same value than
    IS_CONSTANT_ARRAY had.

**Comment by zenovich** [comment]
Fixed in #73
