### ISSUE TITLE
1.0.3 breaks sessions on php 5.3, 1.0.4 removes user functions too early

### ISSUE THREAD

**Issue by cobrafast** [zenovich/runkit#70]
I have just installed release 1.0.3 from `https://github.com/downloads/zenovich/runkit/runkit-1.0.3.tgz` onto PHP `5.3.3-7+squeeze19` and after installation, sessions seem to have become read-only, as well as some functions randomly disappearing during runtime (`Call to undefined function ...() in ....php`) which are definitely there and work without runkit.

Adding `_SESSION` to the `runkit.superglobal` configuration variable has no effect.

Here is my session configuration:

    session.save_handler = files
    session.use_cookies = 1
    session.use_only_cookies = 1
    session.name = PHPSESSID
    session.auto_start = 0
    session.cookie_lifetime = 0
    session.cookie_path = /
    session.cookie_domain =
    session.cookie_httponly =
    session.serialize_handler = php
    session.gc_probability = 1
    session.gc_divisor = 1000
    session.gc_maxlifetime = 2100
    session.bug_compat_42 = Off
    session.bug_compat_warn = Off
    session.referer_check =
    session.entropy_length = 0
    session.cache_limiter = nocache
    session.cache_expire = 180
    session.use_trans_sid = 0
    session.hash_function = 0
    session.hash_bits_per_character = 5

**Comment by zenovich** [comment]
Fixed in https://github.com/zenovich/runkit/commit/994630c8e8dd96d94f5707e29974e26213d59749
