### ISSUE TITLE
Make fails on php 5.4.34

### ISSUE THREAD

**Issue by nickmcski** [zenovich/runkit#74]
php 5.4.34 running the make command fails

lakeloui@lakelouise.com [~/pecl/runkit-0.9]# make
/bin/sh /home2/lakeloui/pecl/runkit-0.9/libtool --mode=compile cc  -I. -I/home2/lakeloui/pecl/runkit-0.9 -DPHP_ATOM_INC -I/home2/lakeloui/pecl/runkit-0.9/include -I/home2/lakeloui/pecl/runkit-0.9/main -I/home2/lakeloui/pecl/runkit-0.9 -I/usr/php/54/usr/include/php -I/usr/php/54/usr/include/php/main -I/usr/php/54/usr/include/php/TSRM -I/usr/php/54/usr/include/php/Zend -I/usr/php/54/usr/include/php/ext -I/usr/php/54/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home2/lakeloui/pecl/runkit-0.9/runkit.c -o runkit.lo
libtool: compile:  cc -I. -I/home2/lakeloui/pecl/runkit-0.9 -DPHP_ATOM_INC -I/home2/lakeloui/pecl/runkit-0.9/include -I/home2/lakeloui/pecl/runkit-0.9/main -I/home2/lakeloui/pecl/runkit-0.9 -I/usr/php/54/usr/include/php -I/usr/php/54/usr/include/php/main -I/usr/php/54/usr/include/php/TSRM -I/usr/php/54/usr/include/php/Zend -I/usr/php/54/usr/include/php/ext -I/usr/php/54/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home2/lakeloui/pecl/runkit-0.9/runkit.c  -fPIC -DPIC -o .libs/runkit.o
/home2/lakeloui/pecl/runkit-0.9/runkit.c: In function 'zif_runkit_zval_inspect':
/home2/lakeloui/pecl/runkit-0.9/runkit.c:61: error: 'zval' has no member named 'refcount'
/home2/lakeloui/pecl/runkit-0.9/runkit.c:62: error: 'zval' has no member named 'is_ref'
/home2/lakeloui/pecl/runkit-0.9/runkit.c: At top level:
/home2/lakeloui/pecl/runkit-0.9/runkit.c:69: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'runkit_functions'
/home2/lakeloui/pecl/runkit-0.9/runkit.c:131: error: 'runkit_functions' undeclared here (not in a function)
/home2/lakeloui/pecl/runkit-0.9/runkit.c: In function 'php_runkit_register_auto_global':
/home2/lakeloui/pecl/runkit-0.9/runkit.c:279: warning: passing argument 3 of 'zend_register_auto_global' makes integer from pointer without a cast
/usr/php/54/usr/include/php/Zend/zend_compile.h:680: note: expected 'zend_bool' but argument is of type 'void *'
/home2/lakeloui/pecl/runkit-0.9/runkit.c:279: error: too few arguments to function 'zend_register_auto_global'
/home2/lakeloui/pecl/runkit-0.9/runkit.c: In function 'zm_deactivate_runkit':
/home2/lakeloui/pecl/runkit-0.9/runkit.c:360: warning: passing argument 2 of 'zend_hash_apply' from incompatible pointer type
/usr/php/54/usr/include/php/Zend/zend_hash.h:138: note: expected 'apply_func_t' but argument is of type 'int (*)(char *)'
/home2/lakeloui/pecl/runkit-0.9/runkit.c:370: warning: passing argument 2 of 'zend_hash_apply' from incompatible pointer type
/usr/php/54/usr/include/php/Zend/zend_hash.h:138: note: expected 'apply_func_t' but argument is of type 'int (*)(struct zend_hash_key *)'
/home2/lakeloui/pecl/runkit-0.9/runkit.c:378: warning: passing argument 2 of 'zend_hash_apply_with_arguments' from incompatible pointer type
/usr/php/54/usr/include/php/Zend/zend_hash.h:140: note: expected 'apply_func_args_t' but argument is of type 'int (*)(struct zend_internal_function *, int,  struct __va_list_tag *, struct zend_hash_key *)'

**Comment by zenovich** [comment]
Do not use runkit 0.9. Use runkit 1.0.4 from the master branch here on GitHub.
