### ISSUE TITLE
A proposal: Allow closure as $code for runkit method add and redefine function?

### ISSUE THREAD

**Issue by HallofFamer** [zenovich/runkit#75]
Well, it seems that in the current way runkit works, we will have to wrap our new method code block in a string, which feels like the old create_function() era:
runkit_method_add('Example', 'add', 
                                '$num1, $num2', 'return $num1 + $num2;', 
                                 RUNKIT_ACC_PUBLIC);

While it does work, it is not the ideal solution for metaprogramming. My suggestion is to add a new parameter called $closure, which will replace $arg and $code in the function signature. So:
bool runkit_method_add ( string $classname , string $methodname , string $args , string $code [, int $flags = RUNKIT_ACC_PUBLIC ] )

will become:

bool runkit_method_add(string $classname, string $methodname, callable $closure, [, int $flags = RUNKIT_ACC_PUBLIC ] )

And the code sample I provide above will be a lot more clean to read and maintain:
runkit_method_add('Example', 'add', function($num1, $num2){
                                                           return $num1 + num2;},
                                 RUNKIT_ACC_PUBLIC);

What do you think? Is this possible to achieve, or will it have some problems?

**Comment by zenovich** [comment]
Dreams come true! https://github.com/zenovich/runkit/commit/fcc70cd73e8695fe15b22d88b3547b540e72f464
