### ISSUE TITLE
Help please I have an error in PHP 5.6.11-1~dotdeb+7.1 (cli) (built: Jul 10 2015 17:36:50)

### ISSUE THREAD

**Issue by zuku3000** [zenovich/runkit#85]
loft9046:/tmp/runkit# make
/bin/bash /tmp/runkit/libtool --mode=compile cc -Wdeclaration-after-statement -Werror -Wall -I. -I/tmp/runkit -DPHP_ATOM_INC -I/tmp/runkit/include -I/tmp/runkit/main -I/tmp/runkit -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/runkit/runkit.c -o runkit.lo 
libtool: compile:  cc -Wdeclaration-after-statement -Werror -Wall -I. -I/tmp/runkit -DPHP_ATOM_INC -I/tmp/runkit/include -I/tmp/runkit/main -I/tmp/runkit -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/runkit/runkit.c  -fPIC -DPIC -o .libs/runkit.o
/bin/bash /tmp/runkit/libtool --mode=compile cc -Wdeclaration-after-statement -Werror -Wall -I. -I/tmp/runkit -DPHP_ATOM_INC -I/tmp/runkit/include -I/tmp/runkit/main -I/tmp/runkit -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/runkit/runkit_functions.c -o runkit_functions.lo 
libtool: compile:  cc -Wdeclaration-after-statement -Werror -Wall -I. -I/tmp/runkit -DPHP_ATOM_INC -I/tmp/runkit/include -I/tmp/runkit/main -I/tmp/runkit -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/runkit/runkit_functions.c  -fPIC -DPIC -o .libs/runkit_functions.o
/bin/bash /tmp/runkit/libtool --mode=compile cc -Wdeclaration-after-statement -Werror -Wall -I. -I/tmp/runkit -DPHP_ATOM_INC -I/tmp/runkit/include -I/tmp/runkit/main -I/tmp/runkit -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/runkit/runkit_methods.c -o runkit_methods.lo 
libtool: compile:  cc -Wdeclaration-after-statement -Werror -Wall -I. -I/tmp/runkit -DPHP_ATOM_INC -I/tmp/runkit/include -I/tmp/runkit/main -I/tmp/runkit -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/runkit/runkit_methods.c  -fPIC -DPIC -o .libs/runkit_methods.o
/bin/bash /tmp/runkit/libtool --mode=compile cc -Wdeclaration-after-statement -Werror -Wall -I. -I/tmp/runkit -DPHP_ATOM_INC -I/tmp/runkit/include -I/tmp/runkit/main -I/tmp/runkit -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/runkit/runkit_constants.c -o runkit_constants.lo 
libtool: compile:  cc -Wdeclaration-after-statement -Werror -Wall -I. -I/tmp/runkit -DPHP_ATOM_INC -I/tmp/runkit/include -I/tmp/runkit/main -I/tmp/runkit -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/runkit/runkit_constants.c  -fPIC -DPIC -o .libs/runkit_constants.o
/bin/bash /tmp/runkit/libtool --mode=compile cc -Wdeclaration-after-statement -Werror -Wall -I. -I/tmp/runkit -DPHP_ATOM_INC -I/tmp/runkit/include -I/tmp/runkit/main -I/tmp/runkit -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/runkit/runkit_import.c -o runkit_import.lo 
libtool: compile:  cc -Wdeclaration-after-statement -Werror -Wall -I. -I/tmp/runkit -DPHP_ATOM_INC -I/tmp/runkit/include -I/tmp/runkit/main -I/tmp/runkit -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/runkit/runkit_import.c  -fPIC -DPIC -o .libs/runkit_import.o
/tmp/runkit/runkit_import.c: In function 'php_runkit_import_class_consts':
/tmp/runkit/runkit_import.c:220:21: error: 'IS_CONSTANT_ARRAY' undeclared (first use in this function)
/tmp/runkit/runkit_import.c:220:21: note: each undeclared identifier is reported only once for each function it appears in
/tmp/runkit/runkit_import.c:226:5: error: passing argument 2 of 'zval_update_constant_ex' makes integer from pointer without a cast [-Werror]
In file included from /usr/include/php5/Zend/zend_API.h:30:0,
                 from /usr/include/php5/main/php.h:39,
                 from /tmp/runkit/php_runkit.h:31,
                 from /tmp/runkit/runkit_import.c:22:
/usr/include/php5/Zend/zend_execute.h:164:14: note: expected 'zend_bool' but argument is of type 'void *'
/tmp/runkit/runkit_import.c: In function 'php_runkit_import_class_static_props':
/tmp/runkit/runkit_import.c:289:6: error: passing argument 2 of 'zval_update_constant' makes integer from pointer without a cast [-Werror]
In file included from /usr/include/php5/Zend/zend_API.h:30:0,
                 from /usr/include/php5/main/php.h:39,
                 from /tmp/runkit/php_runkit.h:31,
                 from /tmp/runkit/runkit_import.c:22:
/usr/include/php5/Zend/zend_execute.h:161:14: note: expected 'zend_bool' but argument is of type 'struct zend_class_entry *'
/tmp/runkit/runkit_import.c: In function 'php_runkit_import_class_props':
/tmp/runkit/runkit_import.c:357:21: error: 'IS_CONSTANT_ARRAY' undeclared (first use in this function)
/tmp/runkit/runkit_import.c:363:5: error: passing argument 2 of 'zval_update_constant_ex' makes integer from pointer without a cast [-Werror]
In file included from /usr/include/php5/Zend/zend_API.h:30:0,
                 from /usr/include/php5/main/php.h:39,
                 from /tmp/runkit/php_runkit.h:31,
                 from /tmp/runkit/runkit_import.c:22:
/usr/include/php5/Zend/zend_execute.h:164:14: note: expected 'zend_bool' but argument is of type 'void *'
cc1: all warnings being treated as errors
make: *** [runkit_import.lo] Błąd 1

What I can do?

**Comment by eelf** [comment]
See issue https://github.com/zenovich/runkit/issues/84

**Comment by zuku3000** [comment]
Many thanks @eelf
It's works!
