### ISSUE TITLE
class name with autoload in runkit_method_* not found

### ISSUE THREAD

**Issue by yeluolei** [zenovich/runkit#99]
for example, I have define a class App\Test in app/test.php and I have include autoload manually in the test file ,but runkit_method_\* still can't found the class, even not process into the autoload function.I need to manually require the app/test.php before call runkit_method_\* functions.

```
<?php
require_once 'autoload.php';


runkit_method_redefine(
    'App\Test',
    '__construct',
    '',
    '
    echo 1;
    ',
    RUNKIT_ACC_PUBLIC
);
```

`runkit_method_redefine(): Class App\Test not found in test.php on line 19`

**Comment by zenovich** [comment]
The autoload works when accessing a class. "runkit_method_redefine" doesn't try to access a class. Your code will work fine if you, for example, call
`class_exists('App\Test', true);`
right before redefining.

**Comment by yeluolei** [comment]
thanks, I have found how to fix it~
